### ISSUE TITLE
SPARQL query doesn't provide expected results

### ISSUE THREAD

**Issue by jotaraul** [EmaroLab/armor#2]
Hi There!
This is a SPARQL related issue, but since I've made it work in the Protege SPARQL Query panel, I'm just wondering why the same query doesn't work through ARMOR. The query is not simple, I'm looking for the classes that can take a certain value for a property. To simplify it, let's suppose that I've defined the class Ball with the restriction:

hasSize someValueFrom (Small or Medium)

To retrieve the Classes in the ontology that have in their definitions the possibility to be Small, I do the following: 

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX : OntologyURI

SELECT ?a 

WHERE{ 
    ?a rdfs:subClassOf ?c . 
    ?c owl:onProperty :hasSize ;
    owl:someValuesFrom  ?d  .
    ?d owl:unionOf ?l . 
    ?l rdf:rest*/rdf:first :Small 
}

This works in Protege, but with the same Ontology it doesn't through ARMOR. I can also say that the same query but a bit simplified, only with the first three lines in the WHERE section, show the same issue.

I've noticed that ARMOR do the following before performing the query:

ReasonerMonitor@2a4f8e30 : Classifying Ontology_bridge_reference started at: 05/12/17_19:31:02,621 and ends now. Ontology_bridge_reference [Durarion:27926101ns]

Could that change somehow the ontology?

Any help will be appreciated :)

**Comment by jotaraul** [comment]
I'm almost sure that the Classification of the Ontology changes it, and then the SPARQL query is searching in a different ontology. Is that possible? 

If so, could I disable that somehow?

Thanks again.

**Comment by alessiocpt** [comment]
Hi, sorry for the late reply! I have never used the SPARQL capabilities of ARMOR but I think that @buoncubi had a similar problem. We'll have a look at it!

**Comment by jotaraul** [comment]
Thank you for the reply. Maybe you coud tell me in which file is the SPARQL thing done? Just to see if I could disble the previous classification step, at least temporally. I've been looking for it in AMOR without success

**Comment by buoncubi** [comment]
ARMOR implements a ROS service that uses [AMOR](https://github.com/EmaroLab/multi_ontology_reference) as an interface through OWL ontologies. 
For reasons inherit from other projects, AMOR does not support multiple ontology URI (except for the ontologies automatically loaded by the reasoner, e.g.: [/owl#](http://www.w3.org/2002/07/owl#)). 
If multiple URIs are used, the reasoner still does its job but the results based on addresses not loaded during AMOR references instantiation (OntologyURI) are not accessible through queries.  
For what I understood this seems to be your problem, is it correct?
For avoiding it, be sure that all your OWL entities are within the same ontology address (you can simply modify that from protege but I would suggest you check it from a textual editor as well).

Furthermore, in the [AMOR enquirer](https://github.com/EmaroLab/multi_ontology_reference/edit/master/amor/src/main/java/it/emarolab/amor/owlInterface/OWLEnquirer.java) file you can find the implementation of the SPARQL in related functions. From here you can try to debug the querying behavior having complete access to the OWL library. 
Also, in the same repository but in a different branch, you can find an [example](https://github.com/EmaroLab/multi_ontology_reference/blob/OWLapi5-Benchmarks/amor/src/main/java/it/emarolab/amor/examples/Benchmarks.java) of a query using the [UOBM](https://www.cs.ox.ac.uk/isg/tools/UOBMGenerator/) ontology benchmark (you can find some generated owl file in this [folder](https://github.com/EmaroLab/multi_ontology_reference/tree/OWLapi5-Benchmarks/amor/files/benchmarks)).

Please, give us more details if you still have problems and try to report on this page if you solve it and how as well as other possible considerations. It may be useful for us and others.

Sorry for the late reply.

**Comment by jotaraul** [comment]
Thank you for the reply @buoncubi !

Concerning the multiple-URIs thing, I'm not sure what you mean exactly. I'm adding below the URIs used in my Ontology, as generated by Protege. Maybe you could indicate me if I should edit something from there:

<?xml version="1.0"?>
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:swrlb="http://www.w3.org/2003/11/swrlb#"
    xmlns="http://www.owl-ontologies.com/SemantIROS.owl#"
    xmlns:xsp="http://www.owl-ontologies.com/2005/08/07/xsp.owl#"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:protege="http://protege.stanford.edu/plugins/owl/protege#"
    xmlns:swrl="http://www.w3.org/2003/11/swrl#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
  xml:base="http://www.owl-ontologies.com/SemantIROS.owl">
...

Thank you for your time.

**Comment by buoncubi** [comment]
It is a bit difficult to understand from here but basically, you should have a unique address for all the entities returned by the query. This should be the same used for loading the ontology into ARMOR. 

Have you tried to add or remove the "#" symbol in the *OntologyURI* used in the query? Unfortunately, I cannot test it right now but you could also log the ontology URI from ARMOR (`OWLReferences.getIriOntologyPath()`) and check if it is coherent. Also, have you try with the example I pointed you out in the previous message? 

Also, a brutal test that you can try is to open the ontology with a text editor and replace all the IRI with a unique address (be careful with the *imported* ontologies). In this way, it should work even if it is not so elegant. 

Let us know how it goes!

**Comment by jotaraul** [comment]
Hi @buoncubi ! Sorry for the late reply, I had to pay attention to other stuff and left this a bit.

I've build a toy ontology aiming to reduce and locate the problem. The ontology has a few classes:
```
Thing | Size | Small
             | Medium
             | Big
      | Object | Ball
               | Bed
```
and only one property: hasSize. A Ball hasSize Small or Medium, while a Bed hasSize Big. I've no problems loading it with ARMOR and doing some simple SPARQL queries. For example, asking for all the classes with a superclass:

```
SPARQL query:
PREFIX  :     <http://www.owl-ontologies.com/toy.owl#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>

SELECT  ?a ?values
WHERE
  { ?a  rdfs:subClassOf  ?c 
  }

[TimeOut:NONE].
-----------------------------------------------------------
| a                                              | values |
===========================================================
| <http://www.owl-ontologies.com/toy.owl#Big>    |        |
| <http://www.w3.org/2002/07/owl#Thing>          |        |
| <http://www.owl-ontologies.com/toy.owl#Small>  |        |
| <http://www.owl-ontologies.com/toy.owl#Object> |        |
| <http://www.owl-ontologies.com/toy.owl#Size>   |        |
| <http://www.owl-ontologies.com/toy.owl#Medium> |        |
| <http://www.owl-ontologies.com/toy.owl#Ball>   |        |
| <http://www.w3.org/2002/07/owl#Nothing>        |        |
| <http://www.owl-ontologies.com/toy.owl#Bed>    |        |
-----------------------------------------------------------
```
but with a bit further elaborated queries I don't get the expected answers. For example, querying for the objects that have in their definition the hasSize property and the value of that property, I get an empty answer:

```
SPARQL query:
PREFIX  :     <http://www.owl-ontologies.com/toy.owl#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>

SELECT  ?a ?values
WHERE
  { ?a  rdfs:subClassOf     ?c .
    ?c  owl:onProperty      :hasSize ;
        owl:someValuesFrom  ?values
  }

[TimeOut:NONE].
--------------
| a | values |
==============
--------------
```
while doing the same query through the SPARQL query panel in Protege I get the expected output:
```
a:                values:
Bed             Big
Ball            Small or Medium
```
As commented, I've checked the URIs of concepts in the ontology, and they are all the same.

I've uploaded the ontology just in case you can try it (remove the .txt extension): [toy_ARMOR_enabled.owl.txt](https://github.com/EmaroLab/armor/files/1781862/toy_ARMOR_enabled.owl.txt)

Any idea about what could be happening behind scenes?

Thank you for your time!
