### ISSUE TITLE
SPARQL query doesn't provide expected results

### ISSUE THREAD

**Issue by jotaraul** [EmaroLab/armor#3]
(I've created a new issue given that the [other one ](https://github.com/EmaroLab/armor/issues/2)was closed. If it's re-opened I could delete this issue :) )

Hi @buoncubi ! Sorry for the late reply, I had to pay attention to other stuff and left this a bit.

I've build a toy ontology aiming to reduce and locate the problem. The ontology has a few classes:
```
Thing | Size | Small
             | Medium
             | Big
      | Object | Ball
               | Bed
```
and only one property: hasSize. A Ball hasSize Small or Medium, while a Bed hasSize Big. I've no problems loading it with ARMOR and doing some simple SPARQL queries. For example, asking for all the classes with a superclass:

```
SPARQL query:
PREFIX  :     <http://www.owl-ontologies.com/toy.owl#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>

SELECT  ?a ?values
WHERE
  { ?a  rdfs:subClassOf  ?c 
  }

[TimeOut:NONE].
-----------------------------------------------------------
| a                                              | values |
===========================================================
| <http://www.owl-ontologies.com/toy.owl#Big>    |        |
| <http://www.w3.org/2002/07/owl#Thing>          |        |
| <http://www.owl-ontologies.com/toy.owl#Small>  |        |
| <http://www.owl-ontologies.com/toy.owl#Object> |        |
| <http://www.owl-ontologies.com/toy.owl#Size>   |        |
| <http://www.owl-ontologies.com/toy.owl#Medium> |        |
| <http://www.owl-ontologies.com/toy.owl#Ball>   |        |
| <http://www.w3.org/2002/07/owl#Nothing>        |        |
| <http://www.owl-ontologies.com/toy.owl#Bed>    |        |
-----------------------------------------------------------
```
but with a bit further elaborated queries I don't get the expected answers. For example, querying for the objects that have in their definition the hasSize property and the value of that property, I get an empty answer:

```
SPARQL query:
PREFIX  :     <http://www.owl-ontologies.com/toy.owl#>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>

SELECT  ?a ?values
WHERE
  { ?a  rdfs:subClassOf     ?c .
    ?c  owl:onProperty      :hasSize ;
        owl:someValuesFrom  ?values
  }

[TimeOut:NONE].
--------------
| a | values |
==============
--------------
```
while doing the same query through the SPARQL query panel in Protege I get the expected output:
```
a:                values:
Bed             Big
Ball            Small or Medium
```
As commented, I've checked the URIs of concepts in the ontology, and they are all the same.

I've uploaded the ontology just in case you can try it (remove the .txt extension): [toy_ARMOR_enabled.owl.txt](https://github.com/EmaroLab/armor/files/1781862/toy_ARMOR_enabled.owl.txt)

Any idea about what could be happening behind scenes?

Thank you for your time!

**Comment by jotaraul** [comment]
Hi guys!

Could you take a look at this?

**Comment by Yksunna** [comment]
Hi,
I am facing the same problem: I get an empty answer every time I execute an SPQRL query and without any error code. Do you know the reason?

**Comment by jotaraul** [comment]
Hi @Yksunna !

I hardly worked on this but I couldn't find why it fails. It's a shame, the rest of the package features are amazing, but this reduces its utility.

Cheers.

**Comment by buoncubi** [comment]
Thanks for having highlighted the issue.
I could replicate your error, but I could not fix it yet. 
Unfortunately, now I am involved in another project and I don't have too much time to check this out, but I will try to do my best about it.

In the middle time, please check the `List<> sparql(String, String )` function at the [OWLEnquirer](https://github.com/EmaroLab/multi_ontology_reference/blob/master/amor/src/main/java/it/emarolab/amor/owlInterface/OWLEnquirer.java) file, I believe some error must be there.
You can test it directly from Java (without using ROS) from this [example](https://github.com/EmaroLab/multi_ontology_reference/blob/master/amor/src/main/java/it/emarolab/amor/examples/OWLRefEnquirerExample.java), where you can rely on the entire OWL API

We do not use SPARQL in our application, but we are trying to support them. 
In that function, there are all the operations we do about this type of query.
Take into account that each AMOR ontology reference considers only the IRI you provide when you load an OWL ontology. 
Probably, this is a problem, but today I could not find any solutions.

Please let me know if you find some further clues! I will try to come to you asap!

**Comment by buoncubi** [comment]
We updated the `master` branch of [AMOR](https://github.com/EmaroLab/multi_ontology_reference) where we fixed the SPARQL function.

All the changes are in the `public List<QuerySolution> sparql(String query, Long timeOut)` function of the [OWLEnquirer](https://github.com/EmaroLab/multi_ontology_reference/blob/master/amor/src/main/java/it/emarolab/amor/owlInterface/OWLEnquirer.java) file.
