### ISSUE TITLE
Cannot run CONSTRUCT sparql query in ARMOR

### ISSUE THREAD

**Issue by Elsenosy** [EmaroLab/armor#5]
I want to run CONSTRUCT query but it return nothing

I run the following code: 
`rosservice call /armor_interface_srv "armor_request:
  client_name: 'client3'
  reference_name: 'reference3'
  command: 'QUERY'
  primary_command_spec: 'SPARQL'
  secondary_command_spec: 'FORMATTED'
  args: ['PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX uni: <http://*****.****/university.owl#>

CONSTRUCT{
	?ind rdf:type uni:High_voltage.
}

WHERE{
	?ind rdf:type uni:Voltage.
	?ind uni:bat_voltage ?volt.
	FILTER(?volt>=25)
}
']" `

Thanks

**Comment by buoncubi** [comment]
We recently updated the master branch of [AMOR](https://github.com/EmaroLab/multi_ontology_reference) where we fixed the SPARQL function.
All the changes are in the `public List<QuerySolution> sparql(String query, Long timeOut)` function of the [OWLEnquirer](https://github.com/EmaroLab/multi_ontology_reference/blob/master/amor/src/main/java/it/emarolab/amor/owlInterface/OWLEnquirer.java) file. Please, be sure to have the last version installed.

In that function, we only execute `SELECT`, but we do not explicitly `CONSTRUCT` the query (see [line 1500](https://github.com/EmaroLab/multi_ontology_reference/blob/ce82c281a458bd2223a93411d1c513d1b7ba0740/amor/src/main/java/it/emarolab/amor/owlInterface/OWLEnquirer.java#L1500)).
Probably, for your case, we need to add the `qexec.execConstruct()` command and manage the resulting value. 

We do not use SPARQL very mcuh and unfortunatelly now I do not have time to fix it personally, but I can try to help you.
In case you are going to change that function please, fork AMOR and send us a push request when it is done. 
The patch you are looking for might be usefull for others!
