### ISSUE TITLE
Getting inferred entities (individuals, properites) when reasoning with Pellet reasoner

### ISSUE THREAD

**Issue by Elsenosy** [EmaroLab/armor#6]
Hello, Is there any way to get the inferred entities such as individuals, data - object properties which applied by SWRL rules and Pellet in the ontology?

The same idea applied in owlready2 (python library), check [this](https://owlready2.readthedocs.io/en/latest/reasoning.html)

**Comment by buoncubi** [comment]
Sorry for the extremely late replay. If this response is not relevant for you anymore, I hope it will be for others.

ARMOR cannot write or make access to SWRL rules at run time but it can load an ontology that already implements the rules, and process them through the reasoner, e.g., Pellet.

The rules are evaluated through the `REASON` commands. After that, the `QUERY` command would also returns the entities inferred by the rules. 
In other terms, `QUERY` returns all the related entities, regardless if they are asserted or inferred by the reasoner.
